services:
  # 1. Apache Zookeeper: to coordinate Kafka brokers
  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    container_name: eyego-zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - '2181:2181'

  # 2. Apache Kafka: messaging system
  kafka:
    image: confluentinc/cp-kafka:7.4.0
    container_name: eyego-kafka
    depends_on:
      - zookeeper
    ports:
      - '9092:9092'
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      #
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  # 3. MongoDB: NoSQL database
  mongo:
    image: mongo:6.0
    container_name: eyego-mongo
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db

  # 4. Mongo Express: web-based MongoDB admin interface
  mongo-express:
    image: mongo-express
    container_name: eyego-mongo-express
    restart: always
    ports:
      - '8081:8081'
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://mongo:27017/
    depends_on:
      - mongo

volumes:
  mongo-data:
